<?php
the_post();
get_header();
include('section-intro-video.php');
include('section-top-navigation.php');
include('section-commitment.php');
include('section-location.php');
include('section-category-pathing.php');
include('section-case-study-example.php');
get_footer();
?>
