<?php
// THIS FILE IS AUTOGENERATED, PLEASE DON'T EDIT IT DIRECTLY

return array(
	"Date" => array(
		__( "Date", 'yith-woocommerce-request-a-quote' ),
	),
	"Quote number" => array(
		__( "Quote number", 'yith-woocommerce-request-a-quote' ),
	),
	"Dimensions" => array(
		__( "Dimensions", 'yith-woocommerce-request-a-quote' ),
	),
	"Margin" => array(
		__( "Margin", 'yith-woocommerce-request-a-quote' ),
	),
	"Padding" => array(
		__( "Padding", 'yith-woocommerce-request-a-quote' ),
	),
	"Dotted" => array(
		__( "Dotted", 'yith-woocommerce-request-a-quote' ),
	),
	"Dashed" => array(
		__( "Dashed", 'yith-woocommerce-request-a-quote' ),
	),
	"Height" => array(
		__( "Height", 'yith-woocommerce-request-a-quote' ),
	),
	"Customer info" => array(
		__( "Customer info", 'yith-woocommerce-request-a-quote' ),
	),
	"Add the information about the customer who requested the quote. Placeholders available:" => array(
		__( "Add the information about the customer who requested the quote. Placeholders available:", 'yith-woocommerce-request-a-quote' ),
	),
	"Product Table settings" => array(
		__( "Product Table settings", 'yith-woocommerce-request-a-quote' ),
	),
	"Show product thumbnail" => array(
		__( "Show product thumbnail", 'yith-woocommerce-request-a-quote' ),
	),
	"Show product name" => array(
		__( "Show product name", 'yith-woocommerce-request-a-quote' ),
	),
	"Show product SKU with the product name" => array(
		__( "Show product SKU with the product name", 'yith-woocommerce-request-a-quote' ),
	),
	"Show quantity" => array(
		__( "Show quantity", 'yith-woocommerce-request-a-quote' ),
	),
	"Show price" => array(
		__( "Show price", 'yith-woocommerce-request-a-quote' ),
	),
	"Show total" => array(
		__( "Show total", 'yith-woocommerce-request-a-quote' ),
	),
	"Titles" => array(
		__( "Titles", 'yith-woocommerce-request-a-quote' ),
	),
	"Color" => array(
		__( "Color", 'yith-woocommerce-request-a-quote' ),
	),
	"Border color" => array(
		__( "Border color", 'yith-woocommerce-request-a-quote' ),
	),
	"Items" => array(
		__( "Items", 'yith-woocommerce-request-a-quote' ),
	),
	"Product Table" => array(
		__( "Product Table", 'yith-woocommerce-request-a-quote' ),
	),
	"Add the product table inside the template." => array(
		__( "Add the product table inside the template.", 'yith-woocommerce-request-a-quote' ),
	),
	"Table settings" => array(
		__( "Table settings", 'yith-woocommerce-request-a-quote' ),
	),
	"Background color" => array(
		__( "Background color", 'yith-woocommerce-request-a-quote' ),
	),
	"Subtotal labels" => array(
		__( "Subtotal labels", 'yith-woocommerce-request-a-quote' ),
	),
	"Total settings" => array(
		__( "Total settings", 'yith-woocommerce-request-a-quote' ),
	),
	"Total Table" => array(
		__( "Total Table", 'yith-woocommerce-request-a-quote' ),
	),
	"Add the total table inside the template." => array(
		__( "Add the total table inside the template.", 'yith-woocommerce-request-a-quote' ),
	),
	"Quote Buttons settings" => array(
		__( "Quote Buttons settings", 'yith-woocommerce-request-a-quote' ),
	),
	"Accept quote" => array(
		__( "Accept quote", 'yith-woocommerce-request-a-quote' ),
	),
	"Reject quote" => array(
		__( "Reject quote", 'yith-woocommerce-request-a-quote' ),
	),
	"Button settings" => array(
		__( "Button settings", 'yith-woocommerce-request-a-quote' ),
	),
	"Border radius" => array(
		__( "Border radius", 'yith-woocommerce-request-a-quote' ),
	),
	"Accept | Reject buttons" => array(
		__( "Accept | Reject buttons", 'yith-woocommerce-request-a-quote' ),
	),
	"Add buttons to accept or reject the quote." => array(
		__( "Add buttons to accept or reject the quote.", 'yith-woocommerce-request-a-quote' ),
	),
	"Quote Date type" => array(
		__( "Quote Date type", 'yith-woocommerce-request-a-quote' ),
	),
	"Add the information about the date of the quote." => array(
		__( "Add the information about the date of the quote.", 'yith-woocommerce-request-a-quote' ),
	),
	"Add the number of the quote. Use the placeholder {{quote_number}} to show the quote number." => array(
		__( "Add the number of the quote. Use the placeholder {{quote_number}} to show the quote number.", 'yith-woocommerce-request-a-quote' ),
	),
	"SKU:" => array(
		__( "SKU:", 'yith-woocommerce-request-a-quote' ),
	),
	"Enter your licence key" => array(
		__( "Enter your licence key", 'yith-woocommerce-request-a-quote' ),
	),
	"to unlock 8 quote templates with different designs and styles" => array(
		__( "to unlock 8 quote templates with different designs and styles", 'yith-woocommerce-request-a-quote' ),
	),
	"Builder pdf template: description optionChoose the data information to display." => array(
		_x( "Choose the data information to display.", "Builder pdf template: description option", 'yith-woocommerce-request-a-quote' ),
	),
	"Builder pdf template: optionQuote creation date" => array(
		_x( "Quote creation date", "Builder pdf template: option", 'yith-woocommerce-request-a-quote' ),
	),
	"Builder pdf template: optionExpiring date" => array(
		_x( "Expiring date", "Builder pdf template: option", 'yith-woocommerce-request-a-quote' ),
	),
	"Builder pdf template: optionCurrent date" => array(
		_x( "Current date", "Builder pdf template: option", 'yith-woocommerce-request-a-quote' ),
	),
	"Builder pdf template - Label Footer optionFooter" => array(
		_x( "Footer", "Builder pdf template - Label Footer option", 'yith-woocommerce-request-a-quote' ),
	),
	"Builder pdf template - Description Footer optionUse {PAGENO} to show the number of the page." => array(
		_x( "Use {PAGENO} to show the number of the page.", "Builder pdf template - Description Footer option", 'yith-woocommerce-request-a-quote' ),
	),
);